Update PHP SDK to 2.8.3
razorpay/payment-button-wordpress-plugin pull request #24
Opened 2022-05-06 12:01 UTC by sonyy-m

2022-05-06 12:37 UTC, sofiya02 approved these changes
LGTM

2022-05-06 12:49 UTC, sofiya02 requested changes

2022-05-06 12:49 UTC, sofiya02 commented on includes/rzp-payment-buttons.php
> +            if($i >= $offset && $i < $offset+$per_page)
instead of && replace with and

2022-05-06 12:49 UTC, sofiya02 commented on includes/rzp-subscription-buttons.php
>          if(isset($_GET['orderby']) && isset($_GET['order']))
Use and instead of &&

2022-05-06 12:49 UTC, sofiya02 commented on includes/rzp-subscription-buttons.php
> +            if($i >= $offset && $i < $offset+$per_page)
Use and instead of &&,

2022-05-06 13:57 UTC, sofiya02 commented
LGTM

2022-05-06 13:59 UTC, sofiya02 approved these changes
LGTM

2022-05-12 09:12 UTC, chirag-patel-rp commented on razorpay-sdk/libs/Requests-2.0.0/src/Transport/Curl.php
> +				curl_setopt($this->handle, CURLOPT_SSL_VERIFYPEER, 0);
@sonyy-m why have we disabled SSL verification here?

2022-05-12 09:15 UTC, sonyy-m commented on razorpay-sdk/libs/Requests-2.0.0/src/Transport/Curl.php
> +				curl_setopt($this->handle, CURLOPT_SSL_VERIFYPEER, 0);
@chirag-patel-rp It is from external requests library [https://github.com/WordPress/Requests](https://github.com/WordPress/Requests)

2022-05-18 07:10 UTC, merged